services:
  - type: web
    name: shl-assessment-api
    env: python
    plan: free
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_layer.service_bootstrap:app --host 0.0.0.0 --port $PORT
